CREATE OR REPLACE VIEW {{ DATABASE }}.{{ SCHEMA }}.CUSTOMER_ORDERS AS
SELECT 
    c.CUSTOMER_ID,
    c.NAME,
    c.EMAIL,
    o.ORDER_ID,
    o.PRODUCT,
    o.QUANTITY,
    o.PRICE,
    o.ORDER_DATE
FROM {{ BRONZE_DB }}.{{ BRONZE_SCHEMA }}.CUSTOMERS c
JOIN {{ BRONZE_DB }}.{{ BRONZE_SCHEMA }}.ORDERS o
  ON c.CUSTOMER_ID = o.CUSTOMER_ID;
