USE {{ DATABASE }};
USE SCHEMA {{ SCHEMA }};

CREATE OR REPLACE TABLE {{ DATABASE }}.{{ SCHEMA }}.{{ ORDERS_TABLE }} (
    ORDER_ID INT,
    CUSTOMER_ID INT,
    PRODUCT STRING,
    QUANTITY INT,
    PRICE FLOAT,
    ORDER_DATE DATE
);
