CREATE OR REPLACE TABLE {{ DATABASE }}.{{ SCHEMA }}.SALES_SUMMARY AS
SELECT 
    CUSTOMER_ID,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(QUANTITY * PRICE) AS TOTAL_REVENUE,
    MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(ORDER_DATE) AS LAST_ORDER_DATE
FROM {{ SILVER_DB }}.{{ SILVER_SCHEMA }}.CUSTOMER_ORDERS
GROUP BY CUSTOMER_ID;
