[snowflake]
type = "snowflake"
account = "${SNOWFLAKE_ACCOUNT}"
user = "${SNOWFLAKE_USER}"
password = "${SNOWFLAKE_PASSWORD}"
role = "${SNOWFLAKE_ROLE}"
warehouse = "${SNOWFLAKE_WAREHOUSE}"
database = "GOLD"
schema = "DEV"
