config-version: 1
root-folder: '../scripts'
connections-file-path: './connections.toml'
connection-name: bronze
change-history-table: bronze_db.metadata.schemachange.change_history
vars:
  CUSTOMER_TABLE: 'CUSTOMERS'
  secrets:
    CUSTOMER_SECRET: 'super_secret_value'
create-change-history-table: true
autocommit: true
verbose: false
dry-run: false
query-tag: 'bronze_deploy'
